/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstoreapp;

import javax.swing.JOptionPane;

/**
 *
 * @author afoud
 */
public class AddBookGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddBookGUI.class.getName());
    
    private final DBClass db;
    
    private int userId;

    /**
     * Creates new form AddBookGUI
     */
    public AddBookGUI(int userId) {
        initComponents();
        this.userId = userId;
        db = new DBClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book1_radioBttn = new javax.swing.JRadioButton();
        book2_radioBttn = new javax.swing.JRadioButton();
        book3_radioBttn = new javax.swing.JRadioButton();
        book4_radioBttn = new javax.swing.JRadioButton();
        confirm_bttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        basket_bttn = new javax.swing.JButton();
        delete_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        book1_radioBttn.setText("ID : 1, Name : Harry Potter and the Philopher's Stone, Type : Normal, Price : 10");

        book2_radioBttn.setText("ID : 2, Name : Murder on the Orient Express, Type: Normal, Price 14.58");

        book3_radioBttn.setText("ID : 3, Name : The Snowball, Type : School, Price : 14.58");

        book4_radioBttn.setText("ID : 4, Name : $100M Offers, Type : School, Price : 8.99");

        confirm_bttn.setText("Confirm");
        confirm_bttn.addActionListener(this::confirm_bttnActionPerformed);

        jLabel1.setText("Place holder of the search book use case, to allow for the prototype use cases to be tested");

        basket_bttn.setText("Basket");
        basket_bttn.addActionListener(this::basket_bttnActionPerformed);

        delete_bttn.setText("Delete all Books In Basket");
        delete_bttn.addActionListener(this::delete_bttnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book4_radioBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book2_radioBttn)
                    .addComponent(book3_radioBttn)
                    .addComponent(jLabel1)
                    .addComponent(delete_bttn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(confirm_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(basket_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(book1_radioBttn)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(book1_radioBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(book2_radioBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(book3_radioBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(book4_radioBttn)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_bttn)
                    .addComponent(basket_bttn))
                .addGap(18, 18, 18)
                .addComponent(delete_bttn)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Get the books the user wants and add it to their basket
    private void confirm_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_bttnActionPerformed
        // TODO add your handling code here:
        if(book1_radioBttn.isSelected()) {
            db.addToBasket(userId, 1);
        }
        if(book2_radioBttn.isSelected()) {
            db.addToBasket(userId, 2);
        }
        if(book3_radioBttn.isSelected()) {
            db.addToBasket(userId, 3);
        }
        if(book4_radioBttn.isSelected()) {
            db.addToBasket(userId, 4);
        }
    }//GEN-LAST:event_confirm_bttnActionPerformed

    // Delete the Books from the Users Basket
    private void delete_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bttnActionPerformed
       if(!db.emptyBasketForUser(userId)) {
           JOptionPane.showMessageDialog(null, "Something went wrong when trying to delete the books from you basket");
       }
    }//GEN-LAST:event_delete_bttnActionPerformed

    private void basket_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basket_bttnActionPerformed
        BasketGUI bgui = new BasketGUI(userId);
        bgui.setVisible(true);
    }//GEN-LAST:event_basket_bttnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basket_bttn;
    private javax.swing.JRadioButton book1_radioBttn;
    private javax.swing.JRadioButton book2_radioBttn;
    private javax.swing.JRadioButton book3_radioBttn;
    private javax.swing.JRadioButton book4_radioBttn;
    private javax.swing.JButton confirm_bttn;
    private javax.swing.JButton delete_bttn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
