/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstoreapp;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author afoud
 */
public class BasketGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BasketGUI.class.getName());
    
    private final DBClass db;
    
    private int userId;
    private ArrayList<ArrayList<String>> basket;
    private ArrayList<Integer> bookIds;
    private double price = 0;
    private boolean rentForSem = false;

    /**
     * Creates new form BasketGUI
     */
    public BasketGUI(int userId) {
        initComponents();
        db = new DBClass();
        this.userId = userId;
        basket = new ArrayList<>();
        bookIds = new ArrayList<>();
        getBasketDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        basket_txtArea = new javax.swing.JTextArea();
        rent_bttn = new javax.swing.JButton();
        buy_bttn = new javax.swing.JButton();
        rentForSem_bttn = new javax.swing.JButton();
        price_txtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rentForSem_txtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Basket");

        basket_txtArea.setColumns(20);
        basket_txtArea.setRows(5);
        jScrollPane1.setViewportView(basket_txtArea);

        rent_bttn.setText("Rent");

        buy_bttn.setText("Buy");
        buy_bttn.addActionListener(this::buy_bttnActionPerformed);

        rentForSem_bttn.setText("Rent for Semester");

        jLabel2.setText("Price");

        jLabel3.setText("Available to rent for Semester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentForSem_bttn)
                            .addComponent(rent_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buy_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rentForSem_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(price_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy_bttn)
                    .addComponent(rentForSem_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rent_bttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentForSem_bttn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buy_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_bttnActionPerformed
        if(checkStock()) {
            PurchaseGUI pgui = new PurchaseGUI(userId, price, bookIds);
            pgui.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Not enough stock available");
        }
    }//GEN-LAST:event_buy_bttnActionPerformed
    
    // Gets all the Books in the users Basket and displays them and the price and if it is avaible to rent for the semester
    private void getBasketDetail() {
        this.basket = db.getUserBasket(userId);
        boolean typeNormal = false;
        boolean typeSchool = false;
        
        for(ArrayList<String> b : basket) {
            basket_txtArea.append("\n Name: " + b.get(1) +
                    ", ISBN: " + b.get(2) +
                    ", Author: " + b.get(3) +
                    ", Category: " + b.get(4) +
                    ", Description: " + b.get(5) +
                    ", Type: " + b.get(6) +
                    ", Price: " + b.get(7));
            
            this.price = price + Double.parseDouble(b.get(7));
            
            if("normal".equals(b.get(6))) {
                typeNormal = true;
            }
            else if("School".equals(b.get(6))) {
                typeSchool = true;
            }
            
            this.bookIds.add(Integer.valueOf(b.get(0)));
        }
        
        price_txtField.setText(Double.toString(price));
        
        if(!typeNormal && typeSchool) {
            rentForSem = true;
        }
        
        if(rentForSem) {
            rentForSem_txtField.setText("Yes");
        }
        else {
            rentForSem_txtField.setText("No");
        }
    }
    
    private boolean checkStock() {
        boolean enoughStock = true;
        Map<Integer, Integer> amountForEachBook = new HashMap<>();
        
        for(Integer b : bookIds) {
            amountForEachBook.put(b, amountForEachBook.getOrDefault(b, 0) + 1);
        }
        
        for(Map.Entry<Integer, Integer> book : amountForEachBook.entrySet()) {
            if(!db.checkStock(book.getKey(), book.getValue())) {
                enoughStock = false;
            }
        }
        
        return enoughStock;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea basket_txtArea;
    private javax.swing.JButton buy_bttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price_txtField;
    private javax.swing.JButton rentForSem_bttn;
    private javax.swing.JTextField rentForSem_txtField;
    private javax.swing.JButton rent_bttn;
    // End of variables declaration//GEN-END:variables
}
