/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstoreapp;

import javax.swing.JOptionPane;

/**
 *
 * @author afoud
 */
public class LoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginGUI.class.getName());
    
    private final DBClass db;
    
    private int userId = 0;
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        
        db = new DBClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email_txtField = new javax.swing.JTextField();
        password_txtField = new javax.swing.JTextField();
        signup_bttn = new javax.swing.JButton();
        login_bttn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        name_txtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email");

        jLabel2.setText("Password");

        signup_bttn.setText("Sign up");
        signup_bttn.addActionListener(this::signup_bttnActionPerformed);

        login_bttn.setText("Log in");
        login_bttn.addActionListener(this::login_bttnActionPerformed);

        jLabel3.setText("Name ( Only Required for Signing up )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(signup_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addComponent(login_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(email_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(password_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup_bttn)
                    .addComponent(login_bttn))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Login Method
    private void login_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_bttnActionPerformed
        try {
            String email = email_txtField.getText().toLowerCase();
            String password = password_txtField.getText();
            
            this.userId = db.loginUser(email, password);
            
            if(userId == 0) {
                JOptionPane.showMessageDialog(null,"User not found, Please make sure your details are correct or Sign up");
            }
            else {
                System.out.println(userId);
                AddBookGUI abGUI = new AddBookGUI(userId);
                abGUI.setVisible(true);
                setVisible(false);
            }
        }
        catch(Exception e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_login_bttnActionPerformed

    // Signup Method
    private void signup_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_bttnActionPerformed
        try{
            String name = name_txtField.getText().toLowerCase();
            String email = email_txtField.getText();
            String password = password_txtField.getText();
            
            this.userId = db.createUser(name, email, password);
            
            if(userId == 0) {
                JOptionPane.showMessageDialog(null,"Email is already in use");
            }
            else if(userId == -1) {
                JOptionPane.showMessageDialog(null,"Something has gone wrong, Please try again");
            }
            else {
                System.out.println(userId);
                // Open new GUI and Pass the userId
            }
        }
        catch(Exception e) {
            
        }
    }//GEN-LAST:event_signup_bttnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_txtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login_bttn;
    private javax.swing.JTextField name_txtField;
    private javax.swing.JTextField password_txtField;
    private javax.swing.JButton signup_bttn;
    // End of variables declaration//GEN-END:variables
}
