/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstoreapp;

import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author afoud
 */
public class PurchaseGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PurchaseGUI.class.getName());

    private Payment payment;
    private DBClass db;

    private int userId;
    private double price;
    private ArrayList<Integer> bookIds;

    int cardNumber;
    int cardCvv;
    YearMonth yearMonth;

    /**
     * Creates new form PurchaseGUI
     */
    public PurchaseGUI(int userId, double price, ArrayList<Integer> bookIds) {
        initComponents();

        this.userId = userId;
        this.price = price;
        this.bookIds = bookIds;

        price_txtField.setText(Double.toString(price));

        this.payment = new Payment(price);
        this.db = new DBClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirm_bttn = new javax.swing.JButton();
        price_txtField = new javax.swing.JTextField();
        cNumber_txtField = new javax.swing.JTextField();
        date_txtField = new javax.swing.JTextField();
        cvv_txtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        confirm_bttn.setText("Confirm");
        confirm_bttn.addActionListener(this::confirm_bttnActionPerformed);

        jLabel1.setText("Card Number");

        jLabel2.setText("Expire Date");

        jLabel3.setText("CVV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirm_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cNumber_txtField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(price_txtField)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 63, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(date_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cvv_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(price_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNumber_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvv_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(confirm_bttn)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_bttnActionPerformed
        // Get all the data to pase to the payment provider
        try {
            this.cardNumber = Integer.parseInt(cNumber_txtField.getText());

            // Format the correct date as would be seen on the card
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/yy");
            this.yearMonth = YearMonth.parse(date_txtField.getText(), formatter);

            this.cardCvv = Integer.parseInt(cvv_txtField.getText());

            // Run the payment check and the database updates
            if (payment.takePayment(cardNumber, yearMonth, cardCvv)
                    && db.recordTransaction(userId, bookIds, price, "Purchase")
                    && db.emptyBasketForUser(userId)) {
                // If successful update the stock
                for (Integer b : bookIds) {
                    db.updateStock(b, 1);
                }
                // Show confirm message to the user
                JOptionPane.showMessageDialog(null, "Payment Successful");
            } 
            else {
                // If anything goes wrong show error message
                JOptionPane.showMessageDialog(null, "Something went wrong");
            }

        } 
        catch(DateTimeParseException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please make sure that your card details are correct " + e);
        }


    }//GEN-LAST:event_confirm_bttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cNumber_txtField;
    private javax.swing.JButton confirm_bttn;
    private javax.swing.JTextField cvv_txtField;
    private javax.swing.JTextField date_txtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField price_txtField;
    // End of variables declaration//GEN-END:variables
}
