/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstoreapp;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author afoud
 */

// This class will be used for both the Rent and Rent for Semester as they operate the same way, just utilizes different information
public class RentGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentGUI.class.getName());
    
    private DBClass db;
    
    private int userId;
    private ArrayList<Integer> bookIds;
    private String rentType;
    private int normalRentPeriod = 2; // 2 weeks from present day
    private int semesterRentPeriod = 4; // 4 months from present day ( 3 months for lectures, 1 month of exams )
    private LocalDate dueDate;
    private String displayedDueDate;

    /**
     * Creates new form RentGUI
     */
    public RentGUI(int userId, ArrayList<Integer> bookIds, String rentType) {
        initComponents();
        
        this.userId = userId;
        this.bookIds = bookIds;
        this.rentType = rentType;
        
        this.db = new DBClass();
        
        rentType_label.setText(rentType);
        
        // Choose how long to rent the book(s) depending on the rentType
        LocalDate now = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yy");
        if("Rent".equals(rentType)) {
            this.dueDate = now.plusWeeks(normalRentPeriod);
            
            this.displayedDueDate = formatter.format(dueDate);
            
            due_txtField.setText(displayedDueDate);
        }
        else {
            this.dueDate = now.plusMonths(semesterRentPeriod);
            
            this.displayedDueDate = formatter.format(dueDate);
            
            due_txtField.setText(displayedDueDate);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentType_label = new javax.swing.JLabel();
        due_txtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        confirm_bttn = new javax.swing.JButton();
        back_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rentType_label.setText("jLabel1");

        jLabel2.setText("Due Date");

        confirm_bttn.setText("Confirm");
        confirm_bttn.addActionListener(this::confirm_bttnActionPerformed);

        back_bttn.setText("Back");
        back_bttn.addActionListener(this::back_bttnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentType_label, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(due_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(confirm_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rentType_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(due_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_bttn)
                    .addComponent(back_bttn))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Runs when the user confirms the return date
    // Records the transaction including the return date and empties the user's basket and update the stock of the books rented
    private void confirm_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_bttnActionPerformed
        if(db.recordTransaction(userId, bookIds, rentType, dueDate) && db.emptyBasketForUser(userId)){
            for (Integer b : bookIds) {
                    db.updateStock(b, 1);
                }
            JOptionPane.showMessageDialog(null, "Rent Successful \n Due back on the: " + displayedDueDate);
            AddBookGUI abGUI = new AddBookGUI(userId);
            abGUI.setVisible(true);
            setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(null, "Something when wrong");
        }
    }//GEN-LAST:event_confirm_bttnActionPerformed

    // Go back to the basket
    private void back_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bttnActionPerformed
        BasketGUI bgui = new BasketGUI(userId);
        bgui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_bttnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_bttn;
    private javax.swing.JButton confirm_bttn;
    private javax.swing.JTextField due_txtField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel rentType_label;
    // End of variables declaration//GEN-END:variables
}
